<div class="wrap">
    <h2>H5P xAPI Settings</h2>

    <h3>About</h3>
    <p>
        This plugin enables all 
        <a href="https://tincanapi.com/statements-101/" target="_blank">xAPI statements</a>
        generated by
        <a href="https://h5p.org/" target="_blank">H5P</a> to be stored in
        a remote <a href="http://www.adlnet.org/tla/lrs.html" target="_blank">LRS</a>, e.g.
        <a href="http://learninglocker.net/" target="_blank">Learning Locker</a> and
        <a href="https://lrs.adlnet.gov/xAPI/" target="_blank">ADL LRS</a>.
    </p>

    <h3>xAPI Endpoint Settings</h3>
    <p>
        The settings in this section specifies the URL and credentials when connecting to
        the LRS to store the statements.<br/><br/>
        If you want to disable this module, leave the <b>xAPI Endpoint URL</b> field blank.
    </p>
    <form method="post" action="options.php">
        <?php settings_fields( 'h5pxapi' ); ?>
        <?php do_settings_sections( 'h5pxapi' ); ?>
        <table class="form-table">
            <tr valign="top">
                <th scope="row">xAPI Endpoint URL</th>
                <td>
                    <input type="text" name="h5pxapi_endpoint_url" 
                        value="<?php echo esc_attr(get_option("h5pxapi_endpoint_url")); ?>" 
                        class="regular-text"/>
                </td>
            </tr>

            <tr valign="top">
                <th scope="row">xAPI Username</th>
                <td>
                    <input type="text" name="h5pxapi_username" 
                        value="<?php echo esc_attr(get_option("h5pxapi_username")); ?>" 
                        class="regular-text"/>
                </td>
            </tr>

            <tr valign="top">
                <th scope="row">xAPI Password</th>
                <td>
                    <input type="text" name="h5pxapi_password" 
                        value="<?php echo esc_attr(get_option("h5pxapi_password")); ?>" 
                        class="regular-text"/>
                </td>
            </tr>
        </table>

        <?php submit_button(); ?>
    </form>
</div>